# Taps
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'dbt-labs/dbt'
cask 'font-sauce-code-pro-nerd-font'

# Zsh Plugins
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

# Binaries
brew 'autojump'
brew 'exa'
brew 'fd'
brew 'fzf'
brew 'htop'
brew 'neofetch'
brew 'pandoc'
brew 'ripgrep'
brew 'sd'
brew 'starship'
brew 'stow'
brew 'tmux'
brew 'wget'

# Dev
brew 'git'
brew 'pyright'
brew 'rust-analyzer'
brew 'go'
brew 'gopls'
brew 'node'
brew 'prettier'
brew 'lua'
brew 'luarocks'
brew 'lua-language-server'
brew 'neovim'
brew 'vim'
