[directory]
read_only = " "

[memory_usage]
symbol = " "

[package]
# disabled = true
symbol = " "

[docker_context]
symbol = " "

[aws]
symbol = "  "

[conda]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[golang]
symbol = " "

[lua]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[scala]
symbol = " "

[ruby]
symbol = " "
