[character]
success_symbol = "[❯](red)"

[directory]
style = "yellow"

[hostname]
ssh_only = false
style = 'blue'
format = "[$hostname]($style) "

[package]
disabled = true

[git_branch]
style = "green"

[git_status]
style = "red"
