[directory]
read_only = " "
style = "blue"

[memory_usage]
symbol = " "

[package]
# disabled = true
symbol = " "

[docker_context]
symbol = " "

[aws]
symbol = "  "

[conda]
symbol = " "

[python]
symbol = " "
style = 'blue'

[rust]
symbol = " "
style = 'blue'

[golang]
symbol = " "
style = 'blue'

[lua]
symbol = " "
style = 'blue'

[java]
symbol = " "
style = 'blue'

[julia]
symbol = " "
style = 'blue'

[scala]
symbol = " "
style = 'blue'

[ruby]
symbol = " "
style = 'blue'
