add_newline = false

[line_break]
disabled = true

[directory]
read_only = "  "
read_only_style = "white"

[git_branch]
symbol = " "
style = "bold #d78700"

[docker_context]
symbol = " "

[gcloud]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "
