# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[git_branch]
symbol = " "
style = "bold #d78700"

[golang]
symbol = " "
style = "blue"

[rust]
symbol = " "
style = "blue"

[python]
symbol = " "
style = "blue"

[lua]
symbol = " "
style = "blue"
