add_newline = false

[line_break]
disabled = true

[directory]
style = "bold white"
read_only = "  "
read_only_style = "white"

[jobs]
symbol = " "

[git_branch]
symbol = " "
style = "bold 202"

[git_status]
style = "bold yellow"

[docker_context]
symbol = " "

[gcloud]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "
