add_newline = false

[line_break]
disabled = true

[package]
disabled = true

[directory]
style = "bold white"
read_only = "  "
read_only_style = "white"

[jobs]
symbol = " "

[git_branch]
symbol = " "
style = "bold 202"

[git_status]
style = "bold yellow"

[docker_context]
symbol = " "
style = "blue"

[gcloud]
symbol = " "
style = "blue"

[golang]
symbol = " "
style = "blue"

[java]
symbol = " "
style = "blue"

[julia]
symbol = " "
style = "blue"

[lua]
symbol = " "
style = "blue"

[nodejs]
symbol = " "
style = "blue"

[python]
symbol = " "
style = "blue"

[ruby]
symbol = " "
style = "blue"

[rust]
symbol = " "
style = "blue"

[scala]
symbol = " "
style = "blue"

[swift]
symbol = "ﯣ "
style = "blue"
