# Taps
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

# Browser
cask 'firefox'
cask 'google-chrome'

# Terminal, shells and plugins
cask 'alacritty'
cask 'iterm2'
brew 'bash'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

# Development
brew 'git'
brew 'python'
brew 'rustup'
brew 'go'
brew 'node'
brew 'r'
cask 'rstudio'
cask 'virtualbox'
cask 'vagrant'

# Editors and IDEs
brew 'neovim'
brew 'vim'
cask 'sublime-text'
cask 'pycharm'
cask 'datagrip'
cask 'gephi'

# Productivity tools
cask 'notion'
cask 'typora'
cask 'slack'

# Binaries
brew 'autojump'
brew 'exa'
brew 'fzf'
brew 'htop'
brew 'neofetch'
brew 'pandoc'
brew 'ranger'
brew 'ripgrep'
brew 'stow'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'youtube-dl'

# Apps
cask '1password'
cask 'dozer'
cask 'flux'
cask 'keybase'
cask 'rectangle'
cask 'spotify'
cask 'telegram'
cask 'whatsapp'

# Fonts
cask 'font-sauce-code-pro-nerd-font'

