# Taps
tap 'homebrew/cask-fonts'

# Shells
brew 'bash'
brew 'fish'
brew 'zsh'

# Shell enhacements
brew 'bash-completion'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

# Editor
brew 'neovim'

# Version control
brew 'git'

# Binaries
brew 'bat'      # Cat clone with syntax highlighting
brew 'exa'      # A modern replacement for ls
brew 'htop'     # Monitor system processes
brew 'neofetch' # Notebook specs
brew 'pandoc'   # Swiss-army knife
brew 'ranger'   # Console file manager
brew 'stow'     # Symlinks manager
brew 'tldr'     # Command's examples
brew 'trash'    # Replace rm with trash
brew 'tree'     # Display folder structure
brew 'wget'     # Download files

# Fonts
cask 'font-sauce-code-pro-nerd-font'

# Terminal
cask 'alacritty'
cask 'iterm2'

# Apps
cask '1password'          # Password manager
cask 'cleanmymac'         # MacBook malware and trash removal
cask 'datagrip'           # DataBases IDE - Jet Brains
cask 'dozer'              # Menu bar customization
cask 'evernote'           # Note-taking app
cask 'flux'               # Adjust screen brightness
cask 'gephi'              # Graph visualization
cask 'google-chrome'      # Main browser
cask 'mactex'             # LaTex in your max
cask 'notion'             # Daily planner | Data collection | Notebook
cask 'obsidian'           # Second brain
cask 'pycharm'            # Python IDE - JetBrains
cask 'rectangle'          # Window manager
cask 'rstudio'            # IDE for R
cask 'slack'              # WhatsApp for nerds
cask 'spotify'            # Be Still - The Killers
cask 'sublime-text'       # Alternative text editor
cask 'vagrant'            # Set up remote machines
cask 'virtualbox'         # Set up remote machines
cask 'whatsapp'           # Mr. Zuck

