# Background configuration
window_opacity: 1

# Window configuration
window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 2
    y: 2

  dynamic_padding: true

  decorations: buttonless

window.dynamic_title: true

# Font configuration
font:
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  size: 13.5

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

colors:
  primary:
    background: "#20201d"
    foreground: "#a6a28c"

  cursor:
    text: "#20201d"
    cursor: "#a6a28c"

  normal:
    black: "#20201d"
    red: "#d73737"
    green: "#60ac39"
    yellow: "#ae9513"
    blue: "#6684e1"
    magenta: "#b854d4"
    cyan: "#1fad83"
    white: "#a6a28c"

  bright:
    black: "#7d7a68"
    red: "#d73737"
    green: "#60ac39"
    yellow: "#ae9513"
    blue: "#6684e1"
    magenta: "#b854d4"
    cyan: "#1fad83"
    white: "#fefbec"

  indexed_colors:
    - { index: 16, color: "#b65611" }
    - { index: 17, color: "#d43552" }
    - { index: 18, color: "#292824" }
    - { index: 19, color: "#6e6b5e" }
    - { index: 20, color: "#999580" }
    - { index: 21, color: "#e8e4cf" }

# Cursor configuration
cursor_style: Block
unfocused_hollow_cursor: true
custom_cursor_colors: false

# Mouse configuration
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

# Scrolling configuration
scrolling:
  history: 10000
  multiplier: 3

# Key bindings
key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: Paste, action: Paste }
  - { key: Copy, action: Copy }
  - { key: H, mods: Command, action: Hide }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: K, mods: Command, action: ClearHistory }
  - { key: K, mods: Command, chars: "\x0c" }
  - { key: N, mods: Command, action: "SpawnNewInstance" }
  - { key: Left, mods: Alt, chars: "\x1bb" }
  - { key: Right, mods: Alt, chars: "\x1bf" }

# Live config reload
live_config_reload: true
