# Background configuration
window_opacity: 1

# Window configuration
window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 2
    y: 2

  dynamic_padding: true

  decorations: buttonless

window.dynamic_title: true

# Font configuration
font:
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  size: 13.5

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

colors:
  primary:
    background: "#1a1b26"
    foreground: "#c0caf5"

  normal:
    black: "#15161E"
    red: "#f7768e"
    green: "#9ece6a"
    yellow: "#e0af68"
    blue: "#7aa2f7"
    magenta: "#bb9af7"
    cyan: "#7dcfff"
    white: "#a9b1d6"

  bright:
    black: "#414868"
    red: "#f7768e"
    green: "#9ece6a"
    yellow: "#e0af68"
    blue: "#7aa2f7"
    magenta: "#bb9af7"
    cyan: "#7dcfff"
    white: "#c0caf5"

  indexed_colors:
    - { index: 16, color: "#ff9e64" }
    - { index: 17, color: "#db4b4b" }

# Cursor configuration
cursor_style: Block
unfocused_hollow_cursor: true
custom_cursor_colors: false

# Mouse configuration
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

# Scrolling configuration
scrolling:
  history: 10000
  multiplier: 3

# Key bindings
key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: Paste, action: Paste }
  - { key: Copy, action: Copy }
  - { key: H, mods: Command, action: Hide }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: K, mods: Command, action: ClearHistory }
  - { key: K, mods: Command, chars: "\x0c" }
  - { key: N, mods: Command, action: "SpawnNewInstance" }
  - { key: Left, mods: Alt, chars: "\x1bb" }
  - { key: Right, mods: Alt, chars: "\x1bf" }

# Live config reload
live_config_reload: true
