# Environment
env:
  TERM: xterm-256color

# Window configuration
window:
  opacity: 1
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 2
    y: 2

  dynamic_padding: true

  decorations: buttonless

window.dynamic_title: true

# Font configuration
font:
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  size: 13.5

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

colors:
  primary:
    background: "#282a36"
    foreground: "#f8f8f2"
    bright_foreground: "#ffffff"

  cursor:
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  search:
    matches:
      foreground: "#44475a"
      background: "#50fa7b"
    focused_match:
      foreground: "#44475a"
      background: "#ffb86c"

  footer_bar:
    background: "#282a36"
    foreground: "#f8f8f2"

  hints:
    start:
      foreground: "#282a36"
      background: "#f1fa8c"
    end:
      foreground: "#f1fa8c"
      background: "#282a36"

  line_indicator:
    foreground: None
    background: None

  selection:
    text: CellForeground
    background: "#44475a"

  normal:
    black: "#21222c"
    red: "#ff5555"
    green: "#50fa7b"
    yellow: "#f1fa8c"
    blue: "#bd93f9"
    magenta: "#ff79c6"
    cyan: "#8be9fd"
    white: "#f8f8f2"

  bright:
    black: "#6272a4"
    red: "#ff6e6e"
    green: "#69ff94"
    yellow: "#ffffa5"
    blue: "#d6acff"
    magenta: "#ff92df"
    cyan: "#a4ffff"
    white: "#ffffff"

# Cursor configuration
cursor_style: Block
unfocused_hollow_cursor: true
custom_cursor_colors: false

# Mouse configuration
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

# Scrolling configuration
scrolling:
  history: 10000
  multiplier: 3

# Key bindings
key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: Paste, action: Paste }
  - { key: Copy, action: Copy }
  - { key: H, mods: Command, action: Hide }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: K, mods: Command, action: ClearHistory }
  - { key: K, mods: Command, chars: "\x0c" }
  - { key: N, mods: Command, action: "SpawnNewInstance" }
  - { key: Left, mods: Alt, chars: "\x1bb" }
  - { key: Right, mods: Alt, chars: "\x1bf" }

# Live config reload
live_config_reload: true
