format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$jobs\
$character"""

[directory]
style = 'cyan'

[git_branch]
style = '#c994eb'
format = 'on [$branch]($style) '

[git_status]
style = 'bright-white'
format = '([$all_status$ahead_behind]($style) )'

[character]
success_symbol = '[|](bold blue)'
error_symbol = '[|](bold red)'
